### ISSUE TITLE
Please Help me

### ISSUE THREAD

**Issue by dr-apple** [sumnerboy12/mqtt-gpio-monitor#16]
I become this error:

root@raspberrypi:/mqtt2gpio# python mqtt-gpio-monitor.py
Traceback (most recent call last):
  File "mqtt-gpio-monitor.py", line 344, in <module>
    init_gpio()
  File "mqtt-gpio-monitor.py", line 281, in init_gpio
    GPIO.setup(pin, GPIO.IN, pull_up_down=GPIO.PUD_UP)
ValueError: The channel sent is invalid on a Raspberry Pi

**Comment by sumnerboy12** [comment]
What value is `pin`? I would guess it is not a valid GPIO pin on the RPi.

**Comment by dr-apple** [comment]
Ok have chance the goip's and the script starts....

But how it works ?

Then i send to /mqtt-gpio-monitor/in/21 0 or 1 value it dosen't chance the gpio pin and i dosen't arrvied a mqtt message :-(

**Comment by dr-apple** [comment]
Can you tell me, what for gpio pin are can use ?

**Comment by sumnerboy12** [comment]
I am not sure what you are asking sorry.

**Comment by mdbxz** [comment]
I am guessing the MQTT_TOPIC value in you .ini file contains a trailing slash. Which actually makes your topic "/mqtt-gpio-monitor//in/21" (notice the double slash).

**Comment by sumnerboy12** [comment]
Closed, no activity.
