### ISSUE TITLE
Having trouble with paho mqtt

### ISSUE THREAD

**Issue by ghowell24** [sumnerboy12/mqtt-gpio-monitor#20]
Looks like I am having trouble with paho mqtt and I am hoping you can provide me with some pointers.

- Program appears to connect and definitely monitoring configured pin --> 18, but I get no data published by mqtt.

2017-07-03 11:34:51,235 INFO  Starting mqtt-gpio-monitor
2017-07-03 11:34:51,236 INFO  INFO MODE
2017-07-03 11:34:51,236 DEBUG DEBUG MODE
2017-07-03 11:34:51,237 DEBUG INIFILE = mqtt-gpio-monitor.ini
2017-07-03 11:34:51,238 DEBUG LOGFILE = mqtt-gpio-monitor.log
2017-07-03 11:34:51,246 INFO  RPi.GPIO module detected...
2017-07-03 11:34:51,247 DEBUG Monitoring pins [18]
2017-07-03 11:34:51,269 DEBUG Initialising GPIO using Board numbering
2017-07-03 11:34:51,270 DEBUG Initialising GPIO input pin 18...
2017-07-03 11:34:51,271 DEBUG Connecting to XXX.XXX.XXX.XXX:1883...
2017-07-03 11:34:51,276 DEBUG Pin 18 changed from -1 to 1
2017-07-03 11:40:42,930 DEBUG Pin 18 changed from 1 to 0
2017-07-03 11:41:11,193 DEBUG Pin 18 changed from 0 to 1

-  simple mosquitto_pub --> mosquitto_sub between nodes works without issue (bi-directional)

What version of python and paho-mqtt are you using?

Do you have any other advice? Here is the errors I see at startup....

$ sudo ./mqtt-gpio-monitor.py 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/pi/usr/local/lib/python3.4/threading.py", line 911, in _bootstrap_inner
    self.run()
  File "/home/pi/usr/local/lib/python3.4/threading.py", line 859, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/usr/local/lib/python3.4/site-packages/paho/mqtt/client.py", line 2606, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/home/pi/usr/local/lib/python3.4/site-packages/paho/mqtt/client.py", line 1470, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/home/pi/usr/local/lib/python3.4/site-packages/paho/mqtt/client.py", line 995, in loop
    rc = self.loop_read(max_packets)
  File "/home/pi/usr/local/lib/python3.4/site-packages/paho/mqtt/client.py", line 1273, in loop_read
    rc = self._packet_read()
  File "/home/pi/usr/local/lib/python3.4/site-packages/paho/mqtt/client.py", line 1838, in _packet_read
    rc = self._packet_handle()
  File "/home/pi/usr/local/lib/python3.4/site-packages/paho/mqtt/client.py", line 2291, in _packet_handle
    return self._handle_connack()
  File "/home/pi/usr/local/lib/python3.4/site-packages/paho/mqtt/client.py", line 2349, in _handle_connack
    self.on_connect(self, self._userdata, flags_dict, result)
TypeError: on_connect() takes 3 positional arguments but 4 were given

**Comment by sumnerboy12** [comment]
I don't run this script anymore but I have committed a fix which should hopefully resolve this issue. Could you please test and close the issue if it worked? Thanks!

**Comment by ghowell24** [comment]
confirmed, fix does resolve startup errors..
